### ISSUE TITLE
c5m3 alarm cars wrong color on 2nd round

### ISSUE THREAD

**Issue by Derpduck** [Derpduck/L4D2-Comp-Stripper-Rework#12]
Remove it for now until fixed

**Comment by Derpduck** [comment]
I suspect this has to do with the plugin that makes alarms consistent between teams. Need to find a better implementation of changing the car colors

**Comment by Derpduck** [comment]
Re-opened until the new colors are re-implemented

**Comment by jensewe** [comment]
**l4d_equalise_alarm_cars** does the job, but it features both _EnableCar_ and _DisableCar_. Maybe reversing the changes when **-relay_caralarm_on** is triggered can help. 😃

**Comment by jensewe** [comment]
https://github.com/Target5150/MoYu_Server_Stupid_Plugins/commit/863126085fa17e48191dc9627f68231a997130c0
give it a try? Seems work for me. Still unaware of whether there's side effect and what it is,

**Comment by Derpduck** [comment]
For plugins you should try SirPlease/L4D2-Competitive-Rework or contacting server owners, I don't have any control over which versions of plugins servers use so I can't test this.
I might have a solution to fix this, but it would be good to fix that plugin if there is an issue with it also.

**Comment by Derpduck** [comment]
_**Should**_ be fixed now, needs testing on a Zonemod server though.

**Comment by jensewe** [comment]
> Round 1

![20210208032841](https://user-images.githubusercontent.com/33988868/107157207-bfd0f080-697a-11eb-9312-3ba52f10e423.jpg)
> Round 2

![20210208032848](https://user-images.githubusercontent.com/33988868/107157221-d1b29380-697a-11eb-9b6e-ea532a084686.jpg)

**Comment by Derpduck** [comment]
Were the alarmed cars the same (correct colors)? I see the far left one might not be, but the colours will be different each round.

**Comment by jensewe** [comment]
Nope. Those not painted red (orange) were consistent off-alarm cars. Al least, on 1st round the middle and the left ones are **on**, and the next round they were disabled.

**Comment by Derpduck** [comment]
Opened again as this isssue is still not fix, in the meantime this feature has been removed (again).
Using logic_versus_random COULD fix the issue but sadly does not has it doesn't support PickRandomShuffle, so that we can ensure there are always 4 alarm cars.
This works fine for vanilla without using `l4d_equalise_alarm_cars`, but with that plugin the wrong cars get colored, even though the correct cars are alarmed.
This isn't the plugin's fault (though if it hooked in a slightly different way it might bypass the issue), the way the map determines which cars are alarmed is quite unique and happens slightly after the round starts.

**Comment by Derpduck** [comment]
My solution would be this:
```; --- Make both teams have the same alarms
modify:
{
	match:
	{
		"targetname" "case_random_alarm_disable"
	}
	replace:
	{
		"classname" "logic_versus_random"
	}
	delete:
	{
		"OnCase01" "alarm1-relay_caralarm_offTrigger0-1"
		"OnCase02" "alarm2-relay_caralarm_offTrigger0-1"
		"OnCase03" "alarm3-relay_caralarm_offTrigger0-1"
		"OnCase04" "alarm4-relay_caralarm_offTrigger0-1"
		"OnCase05" "alarm5-relay_caralarm_offTrigger0-1"
		"OnCase06" "alarm6-relay_caralarm_offTrigger0-1"
		"OnCase07" "alarm7-relay_caralarm_offTrigger0-1"
		"OnCase08" "alarm8-relay_caralarm_offTrigger0-1"
	}
	insert:
	{
		"OnRandom01" "alarm1-relay_caralarm_off,Trigger,,0,-1"
		"OnRandom02" "alarm2-relay_caralarm_off,Trigger,,0,-1"
		"OnRandom03" "alarm3-relay_caralarm_off,Trigger,,0,-1"
		"OnRandom04" "alarm4-relay_caralarm_off,Trigger,,0,-1"
		"OnRandom05" "alarm5-relay_caralarm_off,Trigger,,0,-1"
		"OnRandom06" "alarm6-relay_caralarm_off,Trigger,,0,-1"
		"OnRandom07" "alarm7-relay_caralarm_off,Trigger,,0,-1"
		"OnRandom08" "alarm8-relay_caralarm_off,Trigger,,0,-1"
	}
}```

To get this to work without the support of `PickRandomShuffle` on logic_versus_random, the info_gamemode entity that fires these random events would need to be modified to use `PickRandom` instead. However this wouldn't guarantee that 4 cars are always active, as the same random value could be picked more than once, producing fewer alarm cars.

**Comment by jensewe** [comment]
Tried debugging the plugin, and found it failing to actually enable disabled cars, even no error occurs during the whole process. 

As it seems struggling via Stripper, how about script a plugin replacing this? Added that even though the previous solution had worked, the colors of disabled cars would have varied between rounds (tiny but here it is).

A few advantages are:
- Global hook and color changes for alarm cars, as long as they are using the car model and with correctly formated targetname of logic_relay.
- Colors of cars can be stored if changes applied, so consistency is guaranteed.

**Comment by Derpduck** [comment]
I would like to avoid creating plugins for solving problems on specific maps like this where Stripper can and should be used instead.
I think the current alarm car plugin could just store the `rendercolor` of the alarm cars when it checks them on the first round, then apply them on the 2nd round.

These specific cars get set AFTER round_start is called I think though, I'm not too sure what the issue is. But regardless this is something I'm not going to come back to for a while, but if you want to try making a plugin feel free.

**Comment by MartLegion** [comment]
That case car color logic is on almost every map that has a car alarm. Maybe should be better to set a default color to all cars and remove all logic cases, both on stripper.
