### ISSUE TITLE
c3m1 ammo pile on the ferry doesn't trace and stuck the ferry moving back on 2nd round

### ISSUE THREAD

**Issue by jensewe** [Derpduck/L4D2-Comp-Stripper-Rework#14]
"Floats" on the river, and keeps the ferry from arrival for a long period.

![20210124042702](https://user-images.githubusercontent.com/33988868/105613429-6b1b6a80-5dfd-11eb-8ce0-933c3f104d71.png)

**Comment by Derpduck** [comment]
Unfortunately it seems like on the 2nd round the ammo pile loses some of its properties that allow it to attach to the ferry, so a different ammo placement has to be used.
