### ISSUE TITLE
c2m1 motel roof clips sometimes not remove

### ISSUE THREAD

**Issue by ProjectSky** [Derpduck/L4D2-Comp-Stripper-Rework#22]
it often happens on my server, change delay to 15~20 work for me
https://github.com/Derpduck/L4D2-Comp-Stripper-Rework/blob/1bbd28c18998114e90cf644299094869a15cb7fe/cfg/stripper/maps/c2m1_highway.cfg#L1375-L1377

**Comment by Derpduck** [comment]
Is there any line in the server's console logs like the below when this happens?
`
SCRIPT PERF WARNING --- "main" ran long at 12.895902ms
`

Might need to run the server with -developer launch option to see this.

**Comment by ProjectSky** [comment]
> Is there any line in the server's console logs like the below when this happens?
> `SCRIPT PERF WARNING --- "main" ran long at 12.895902ms`
> 
> Might need to run the server with -developer launch option to see this.

added -dev option start servers, tested some maps, no warning
less delay seems to cause OnMapSpawn not work

**Comment by Derpduck** [comment]
Does this happen only on the first round or on both rounds?

Regardless, I've increased the delay across all maps, if it continues to happen post about it here.
It's likely due to the scripts used to spawn the entities taking longer to run than they should.

**Comment by ProjectSky** [comment]
first or second, if the first, the second probably not happen
anyway, i will continue to test it

**Comment by Derpduck** [comment]
No more issues reported so assuming this is fixed.
