### ISSUE TITLE
c11m3/c12m3 bug spots

### ISSUE THREAD

**Issue by 4thyoshino** [Derpduck/L4D2-Comp-Stripper-Rework#24]
https://clips.twitch.tv/ObliviousCogentMosquitoMikeHogu-i33pJnrVsx9x7fgE
Map: Dead air, map 3. able to jump on the top of power station

https://clips.twitch.tv/EntertainingReliableSquirrelBuddhaBar-rgdX8l2kMDHvgc4H
Map: Blood Harvest, map 3. fast way running to the camp spot.

both spot still working on zonemod 1.9.16. so hope can fixed it.

**Comment by Derpduck** [comment]
Blood Harvest one is already fixed here, I'll add the other one to the to-do list.
