### ISSUE TITLE
Maybe one issue in C1M3

### ISSUE THREAD

**Issue by A1oneR** [Derpduck/L4D2-Comp-Stripper-Rework#28]
Sometimes the alert door can be destroyed by tank's punch or survivor's weapon, and the rest of the path will no longer spawn the elevators because of that. I don't know where the problem might be in, so can you lend a help? It will be appreciate of you if you can deal with the issue.

**Comment by Derpduck** [comment]
This issue is caused by certain versions of the ready up plugin that make props unbreakable during ready up. Using the latest ready up plugin from here should fix it https://github.com/SirPlease/L4D2-Competitive-Rework
