### ISSUE TITLE
C4M5 "pre_event_tank_trigger" can trigger by alive Infected

### ISSUE THREAD

**Issue by JQ-WTF** [Derpduck/L4D2-Comp-Stripper-Rework#29]
like title say , its happen on my server.

**Comment by JQ-WTF** [comment]
lt's look like C5M5"filtername" "filter_survivors" is right , not C4M5"filtername" "filter_survivor"

**Comment by Derpduck** [comment]
I'm not able to reproduce this, can you provide any more details?

**Comment by JQ-WTF** [comment]
well, nvm . looks like only my sever can happen , i test on other server its ok . maybe  it has something to do with my modified stripper . and i already change it . sry :(
