### ISSUE TITLE
Single-pickup primaries have no reserve ammo

### ISSUE THREAD

**Issue by jensewe** [Derpduck/L4D2-Comp-Stripper-Rework#3]
Server bases Zonemod 1.9.9 from Competitive Rework with this repo. Happened on c1m1 as well as c4m1, at whose start there're manually spawned primaries. I have no idea whether this is intended.🤔

**Comment by jensewe** [comment]
Btw, it's fine to pick these up during readyup because _sv_infinite_primary_ammo_ is set to 1. Not sure whether this is designed to work that way. If so, please let me know.

**Comment by Derpduck** [comment]
Wrong repo, you want this: https://github.com/SirPlease/L4D2-Competitive-Rework
This repo is purely for map changes

**Comment by Derpduck** [comment]
Mis-read the initial comment. This does seem to be the case, though I would recommend against using these changes currently as they are still in development.

**Comment by Derpduck** [comment]
Fixed in 2025da96cc2994bb222f401178f4b5f6c14eeb38
