### ISSUE TITLE
RNG weapon skin makes guns not absorbed by nearby spawners

### ISSUE THREAD

**Issue by jensewe** [Derpduck/L4D2-Comp-Stripper-Rework#32]
![%$5RP5QKH3Z6PBE1P I{P`G](https://user-images.githubusercontent.com/33988868/129969682-34c0b884-a75e-4792-9859-952ac96baa57.png)

Probably not a big deal but it seems unreasonable to behave like that.

**Comment by Derpduck** [comment]
Not sure if there's much that can be done to fix this, it's simply part of how the weapon spawns work and there is no setting to ignore skins.

**Comment by jensewe** [comment]
Investigated and found it's caused by a RNG plugin setting "m_nSkin" but leaving "m_nWeaponSkin". Very funny that took me around 2 weeks on guns not being absorbed.
