### ISSUE TITLE
[REQ] White forest map 3 fix

### ISSUE THREAD

**Issue by lunatixxx** [Derpduck/L4D2-Comp-Stripper-Rework#33]
Bug survivor stuck forever in a area after scavenge event if raised from ledge: 
https://steamcommunity.com/sharedfiles/filedetails/?id=2354700897

**Comment by lunatixxx** [comment]
There are some stupid hardcoded tanks on this map too at the start, had 3 at same time in versus.

**Comment by lunatixxx** [comment]
Fixed the bug by adding some props.

**Comment by Derpduck** [comment]
Not fixed on this repo so issue will remain open
