### ISSUE TITLE
c5m3 sewer fall damage

### ISSUE THREAD

**Issue by ProjectSky** [Derpduck/L4D2-Comp-Stripper-Rework#35]
* this location will cause 5 fall damage to survivors

![GIF 2021-08-23 11-17-05](https://user-images.githubusercontent.com/16351827/130385381-5c448ed2-666f-4a25-80ac-7c0652caa80a.gif)

```
add:
; --- Prevent sewer fall damage
{
	"classname" "logic_auto"
	"OnMapSpawn" "no_fall_damage,AddOutput,mins -32 -32 -32,0,-1"
	"OnMapSpawn" "no_fall_damage,AddOutput,maxs 32 32 32,0,-1"
	"OnMapSpawn" "no_fall_damage,AddOutput,boxmins -32 -32 -32,0,-1"
	"OnMapSpawn" "no_fall_damage,AddOutput,boxmaxs 32 32 32,0,-1"
	"OnMapSpawn" "no_fall_damage,AddOutput,solid 2,0,-1"
}
{
	"classname" "trigger_multiple"
	"origin" "4216 312 -160"
	"targetname" "no_fall_damage"
	"filtername" "filter_survivor"
	"spawnflags" "1"
	"OnStartTouch" "!activator,IgnoreFallDamageWithoutReset,1,0,-1"
}
```

**Comment by Derpduck** [comment]
I cannot reproduce this on vanilla or on a properly configured competitive server.
Are you sure your sv_gravity is set correctly for a 100 tick server?
Using the TickrateFixes plugin reduces sv_gravity to 750 (default is 800), the only way I can reproduce this is with sv_gravity set to 800.

**Comment by ProjectSky** [comment]
> I cannot reproduce this on vanilla or on a properly configured competitive server.
> Are you sure your sv_gravity is set correctly for a 100 tick server?
> Using the TickrateFixes plugin reduces sv_gravity to 750 (default is 800), the only way I can reproduce this is with sv_gravity set to 800.

* oh i forgot the gravity, my servers set ```sv_gravity 800```
