### ISSUE TITLE
Death Toll map 1 SI ladder not work on round 2

### ISSUE THREAD

**Issue by Target5150** [Derpduck/L4D2-Comp-Stripper-Rework#36]
Title , and screenshot here.

![20210824015914_1](https://user-images.githubusercontent.com/42076548/130495359-fd865479-8c71-45a0-8355-21a4bda937a9.jpg)
![20210824015950_1](https://user-images.githubusercontent.com/42076548/130495367-62a020bf-8654-4413-8463-41a4f39990b4.jpg)

**Comment by Derpduck** [comment]
Looks like the ladder name is not preserved between rounds.

**Comment by Derpduck** [comment]
For now I am removing the affected ladders, replacing them is problematic because the choice of ladders on the maps is limited.
