### ISSUE TITLE
Some unbreakable door on map

### ISSUE THREAD

**Issue by Target5150** [Derpduck/L4D2-Comp-Stripper-Rework#40]
Example:
![20220523205327_1](https://user-images.githubusercontent.com/42076548/169824146-5d8ff744-0a46-46ba-a3dc-d9c811021de8.jpg)
![20220523205406_1](https://user-images.githubusercontent.com/42076548/169824212-4d0485cc-5e1c-42eb-a4ce-fcb95b290382.jpg)

Refer the Diescraper chapter 3 start elevator, survivor just go in those room and AI the tank.
The example screenshot is on DBD chapter 3
And I found same door on Suicide blitz 2 chapter 3, but you can't close after you open it, the DBD m3 you can close and open.
I guess not only those, maybe need care if other map same door existed.

**Comment by fbef0102** [comment]
my solution: delete this model door in global.


```
filter:
; remove unbreakable freezer door
{
	"model" "models/props_doors/doorfreezer01.mdl"
 	"classname" "prop_door_rotating"
}
```
