### ISSUE TITLE
some bugs on "No Mercy: Rehab"

### ISSUE THREAD

**Issue by SomeRandomNoobOlolo** [Derpduck/L4D2-Comp-Stripper-Rework#49]
#### chapter 2
is this surface suppose to be obscured?
[the surface ](https://drive.google.com/file/d/18xkBBi9Sn8RfgLcX85XiD8J6NYBNS6UR/view)

#### chapter 3
if tank punch a gas pump it will disappear after some time like a car, and poor survs will not be able to start the event
[tank vs pumps](https://drive.google.com/drive/folders/10Y3FPeNaGkP_q_8s-jBbD_ZYPweNW-ki)

if bots are passing the map on their own they will get stuck on these boxes, ofc you can takecontrol and lead them, but they will not find the way on their own
[bots vs boxes](https://drive.google.com/drive/folders/1jAzM-HEosSm5HaacQQvzOrYrsirCDiQA)

#### chapter 4
bots constantly getting stuck on this ladder, it's not impossible to climb there, but bots dont like it
[climbing problems](https://drive.google.com/drive/folders/15P9wW0O4127T2crdVoG2PcibCzW7ZyHl)

**Comment by Derpduck** [comment]
Thanks for the bug reports, however this is not the correct place to report them. I will create a discussion thread on the workshop page for any future bug reports once I release the next update.

**Comment by Derpduck** [comment]
Bugs should all be fixed with the new update.
