### ISSUE TITLE
Dead before Dawn small QoL Improvements

### ISSUE THREAD

**Issue by robex** [Derpduck/L4D2-Comp-Stripper-Rework#50]
## Map 1
Tanks on map 1 after around 45% always get AI'd by running back to the saferoom since there is no good place to fight them forward, I think anything after 45% should be banned.

Another potential solution which would require more work could be to block off the right side path with something like a fence/truck/bus.

With the early tank it could be too easy to bring in too many hittables, the car on fire should probably be made non-hittable to compensate, so the tank would have to bring the alarm car in from further away.

![image](https://github.com/Derpduck/L4D2-Comp-Stripper-Rework/assets/23484075/606dc481-bfad-4b9d-a331-a6933ef63d38)

Another possibility is to also move the dumpster located after the alarm car to a more favorable spot for the Tank.

![image](https://github.com/Derpduck/L4D2-Comp-Stripper-Rework/assets/23484075/feb2d94a-76a1-476a-b03e-ea8f3c3677c3)

![image](https://github.com/Derpduck/L4D2-Comp-Stripper-Rework/assets/23484075/f8ad2df3-7627-4e4a-b6b0-258806cce88d)

In the house after the broken down helicopter, common and SI can break the wooden planks covering the door with many hits, allowing the survivors to cut through the stairs choke. There should be a prop added or the planks should be made unbreakable to prevent this.

![image](https://github.com/Derpduck/L4D2-Comp-Stripper-Rework/assets/23484075/692796fc-acc5-4e6b-8352-37a215fb58ed)

## Map 3
_**Probably the most important change:**_ With the 2 damage/hit commons, the time needed to close the door on the event on map 3 **should be reduced** to 4 or 5 seconds. With a good sack rotation you can literally delay the survivors forever making them at minimum lose half their HP but potentially killing them, with still a very long map (and potentially tank) ahead.

Relevant line: https://github.com/Derpduck/L4D2-Comp-Stripper-Rework/blob/master/cfg/stripper/maps/l4d_dbd2dc_clean_up.cfg#L130

It would be a good idea to add a prop/extend the ladder on the vent drop to allow the Tank to climb back over without having to go all the way around the vent, in order to give the Tank a bit more time to catch up to the survivors, reducing the potential for AI. It would also make it a bit nicer for newer players since the alternative way around is a bit of a maze.

![image](https://github.com/Derpduck/L4D2-Comp-Stripper-Rework/assets/23484075/2380db13-d7fb-4d65-8f28-407e8ec64b0f)

There could be a prop added in order to climb back over the wall after the holdout event, this would allow slow survivors to make it back without having to go all the way around (which enables the Tank to cut them off 100% of the time.)

![image](https://github.com/Derpduck/L4D2-Comp-Stripper-Rework/assets/23484075/b4f8b288-76fc-497d-b1d4-1616db8799dd)

The skip over the trash bags at the end should be blocked since it allows the Survivors to skip a choke at the corner.

![image](https://github.com/Derpduck/L4D2-Comp-Stripper-Rework/assets/23484075/fa7cdc5a-50b5-48a8-b9eb-8735a92612a0)

SI can spawn in a few spots in the end saferoom by jumping on the vending machine and table (potentially on the sofas too).

![image](https://github.com/Derpduck/L4D2-Comp-Stripper-Rework/assets/23484075/be68d741-ea73-4d2d-81ba-11e7d9f3c7cf)

**Comment by Derpduck** [comment]
Thanks for the suggestions, I'm looking at making some of these changes in an update soon.

On the map 1 ban range you mentioned there's no good places to fight tank later on in the map, so I was looking at the house where typically survivors would fight it outside and found a few spots where survivors can jump on top of props inside the house to get an advantage. Is something that is known and has been tried, or makes it worth keeping this tank spawn around if it would make it better to fight?

![20230720113930_1](https://github.com/Derpduck/L4D2-Comp-Stripper-Rework/assets/934223/e0aa7c1c-7a01-4cc6-85ac-2fba300b4ca8)
![20230720113937_1](https://github.com/Derpduck/L4D2-Comp-Stripper-Rework/assets/934223/9e23b9a9-c74d-40cf-9641-d05a6f42f55f)
![20230720113944_1](https://github.com/Derpduck/L4D2-Comp-Stripper-Rework/assets/934223/9b4fe2dc-a956-442f-bdf9-461693be2ff7)

**Comment by robex** [comment]
> On the map 1 ban range you mentioned there's no good places to fight tank later on in the map or that any late tank can just be run back to saferoom and AI'd, so I was looking at the house where typically survivors would fight it outside and found a few spots where survivors can jump on top of props inside the house to get an advantage. Is this a known thing that has been tried, and would this make it worth keeping a late tank spawn unblocked if this is a better way to play it if you couldn't run back?

I don't think its ever been tried since tanks cannot spawn that late. It might be a fine room to fight Tank and would add some variety to the map, but you'd have to make sure that the tanks cannot spawn from the 45% range until that one-way drop in the house (to prevent AI's running all the way back) and then not much further away from the house exit, to ensure that it's actually fought in the room and it doesn't spawn bugged behind the event or something.
